- name: Create backup configuration ConfigMap
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: restore-config
        namespace: "{{ inventory_hostname }}"
        labels:
          app: wp-veritas
      data:
        config.yaml: |
          {% if inventory_environment != 'prod' %}
          test:
            s3:
              bucket: "{{ keybase_secrets.test.s3.bucket }}"
              endpoint: "https://s3.epfl.ch"
              secretName: "s3-backup-credentials"
            media:
              claimName: "wordpress-data"
            api:
              url: "https://wp-veritas-test.epfl.ch/api/v2/sites"
          {% endif %}
          prod:
            s3:
              bucket: "{{ keybase_secrets.prod.s3.bucket }}"
              endpoint: "https://s3.epfl.ch"
              secretName: "{{ 's3-prod-ro-credentials' if inventory_environment == 'test' else 's3-backup-credentials' }}"
            media:
              claimName: "wordpress-data{{ '-prod' if inventory_environment == 'test' else '' }}"
            api:
              url: "https://wp-veritas.epfl.ch/api/v2/sites"
