- name: Robot Pull
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ app_name }}-pull-secret"
        namespace: "{{ inventory_hostname }}"
      data:
        .dockerconfigjson: "{{ robot_pull }}"

- name: Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ inventory_hostname }}"
      stringData:
        TELEGRAM_BOT_TOKEN: "{{ secrets.telegram.token }}"
        TELEGRAM_IDS: "{{ secrets.telegram.channels | join(',') | string }}"
        EPFL_API_PASSWORD: "{{ secrets.api.password }}"
        EPFL_API_USERNAME: "{{ secrets.api.username }}"
        EPFL_API_URL: "{{ secrets.api.url }}"
        AUTH_MICROSOFT_ENTRA_ID: "{{ secrets.oidc.id }}"
        AUTH_MICROSOFT_ENTRA_SECRET: "{{ secrets.oidc.secret }}"
        AUTH_MICROSOFT_ENTRA_ISSUER: "{{ secrets.oidc.issuer }}"
        AUTH_SECRET: "{{ secrets.auth.secret }}"
        MONGO_URI: mongodb://{{ secrets.mongodb.user }}:{{ secrets.mongodb.password }}@{{ secrets.mongodb.host }}.epfl.ch/{{ secrets.mongodb.name }}
        REDIS_URI: redis://{{ redis_name }}:6379
        UMAMI_URL_SCRIPT: "{{ secrets.analytics.umami.url_script }}"
        UMAMI_WEBSITE_ID: "{{ secrets.analytics.umami.website_id }}"
