all:
  hosts:
    wp-veritas-prod-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0041p-wordpress
      inventory_environment: prod
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars:
    route:
      host: wp-veritas.epfl.ch
      availability: public
    awx_url: https://awx-wwp.epfl.ch/api/v2/job_templates/32/launch/
    tequila_allowed_hosts: 10.180.21.0/24
    tag: 3.6.5
