all:
  hosts:
    wp-veritas-test-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0041t-wordpress
      inventory_environment: test
      ansible_python_interpreter: '{{ ansible_playbook_python }}'

  vars:
    route:
      host: wp-veritas-test.epfl.ch
      availability: private

    WP_VERITAS_AWX_URL: https://awx-poc-vpsi.epfl.ch/api/v2/job_templates/148/launch/
    
    tag: dev.20250204151936.54922f7.5
 
