export const LANGUAGES = {
	AF: { name: "Afrikaans", locale: "af", slug: "af", rtl: 0, term_group: 0, flag: "za", common: "Afrikaans" },
	AM: { name: "አማርኛ", locale: "am", slug: "am", rtl: 0, term_group: 1, flag: "et", common: "አማርኛ" },
	AR: { name: "العربية", locale: "ar", slug: "ar", rtl: 1, term_group: 2, flag: "arab", common: "العربية" },
	ARG: { name: "Aragonés", locale: "arg", slug: "arg", rtl: 0, term_group: 3, flag: "es", common: "Aragonés" },
	ARY: { name: "العربية المغربية", locale: "ary", slug: "ary", rtl: 1, term_group: 4, flag: "ma", common: "العربية المغربية" },
	AS: { name: "অসমীয়া", locale: "as", slug: "as", rtl: 0, term_group: 5, flag: "in", common: "অসমীয়া" },
	AZ: { name: "Azərbaycan", locale: "az", slug: "az", rtl: 0, term_group: 6, flag: "az", common: "Azərbaycan" },
	AZB: { name: "گؤنئی آذربایجان", locale: "azb", slug: "azb", rtl: 1, term_group: 7, flag: "az", common: "گؤنئی آذربایجان" },
	BEL: { name: "Беларуская мова", locale: "bel", slug: "bel", rtl: 0, term_group: 8, flag: "by", common: "Беларуская мова" },
	BG_BG: { name: "български", locale: "bg_BG", slug: "bg", rtl: 0, term_group: 9, flag: "bg", common: "български BG" },
	BN_BD: { name: "বাংলা", locale: "bn_BD", slug: "bn", rtl: 0, term_group: 10, flag: "bd", common: "বাংলা BD" },
	BO: { name: "བོད་ཡིག", locale: "bo", slug: "bo", rtl: 0, term_group: 11, flag: "tibet", common: "བོད་ཡིག" },
	BS_BA: { name: "Bosanski", locale: "bs_BA", slug: "bs", rtl: 0, term_group: 12, flag: "ba", common: "Bosanski BA" },
	CA: { name: "Català", locale: "ca", slug: "ca", rtl: 0, term_group: 13, flag: "catalonia", common: "Català" },
	CEB: { name: "Cebuano", locale: "ceb", slug: "ceb", rtl: 0, term_group: 14, flag: "ph", common: "Cebuano" },
	CKB: { name: "کوردی", locale: "ckb", slug: "ckb", rtl: 1, term_group: 15, flag: "kurdistan", common: "کوردی" },
	CS_CZ: { name: "Čeština", locale: "cs_CZ", slug: "cs", rtl: 0, term_group: 16, flag: "cz", common: "Čeština CZ" },
	CY: { name: "Cymraeg", locale: "cy", slug: "cy", rtl: 0, term_group: 17, flag: "wales", common: "Cymraeg" },
	DA_DK: { name: "Dansk", locale: "da_DK", slug: "da", rtl: 0, term_group: 18, flag: "dk", common: "Dansk DK" },
	DE_AT: { name: "Deutsch", locale: "de_AT", slug: "de", rtl: 0, term_group: 19, flag: "at", common: "Deutsch AT" },
	DE_CH: { name: "Deutsch", locale: "de_CH", slug: "de", rtl: 0, term_group: 20, flag: "ch", common: "Deutsch CH" },
	DE_CH_INFORMAL: { name: "Deutsch", locale: "de_CH_informal", slug: "de", rtl: 0, term_group: 21, flag: "ch", common: "Deutsch CH informal" },
	DE_DE: { name: "Deutsch", locale: "de_DE", slug: "de", rtl: 0, term_group: 22, flag: "de", common: "Deutsch" },
	DE_DE_FORMAL: { name: "Deutsch", locale: "de_DE_formal", slug: "de", rtl: 0, term_group: 23, flag: "de", common: "Deutsch DE formal" },
	DSB: { name: "Dolnoserbšćina", locale: "dsb", slug: "dsb", rtl: 0, term_group: 24, flag: "de", common: "Dolnoserbšćina" },
	DZO: { name: "རྫོང་ཁ", locale: "dzo", slug: "dzo", rtl: 0, term_group: 25, flag: "bt", common: "རྫོང་ཁ" },
	EL: { name: "Ελληνικά", locale: "el", slug: "el", rtl: 0, term_group: 26, flag: "gr", common: "Ελληνικά" },
	EN_AU: { name: "English", locale: "en_AU", slug: "en", rtl: 0, term_group: 27, flag: "au", common: "English AU" },
	EN_CA: { name: "English", locale: "en_CA", slug: "en", rtl: 0, term_group: 28, flag: "ca", common: "English CA" },
	EN_GB: { name: "English", locale: "en_GB", slug: "en", rtl: 0, term_group: 29, flag: "gb", common: "English GB" },
	EN_NZ: { name: "English", locale: "en_NZ", slug: "en", rtl: 0, term_group: 30, flag: "nz", common: "English NZ" },
	EN_US: { name: "English", locale: "en_US", slug: "en", rtl: 0, term_group: 31, flag: "us", common: "English" },
	EN_ZA: { name: "English", locale: "en_ZA", slug: "en", rtl: 0, term_group: 32, flag: "za", common: "English ZA" },
	EO: { name: "Esperanto", locale: "eo", slug: "eo", rtl: 0, term_group: 33, flag: "esperanto", common: "Esperanto" },
	ES_AR: { name: "Español", locale: "es_AR", slug: "es", rtl: 0, term_group: 34, flag: "ar", common: "Español AR" },
	ES_CL: { name: "Español", locale: "es_CL", slug: "es", rtl: 0, term_group: 35, flag: "cl", common: "Español CL" },
	ES_CO: { name: "Español", locale: "es_CO", slug: "es", rtl: 0, term_group: 36, flag: "co", common: "Español CO" },
	ES_CR: { name: "Español", locale: "es_CR", slug: "es", rtl: 0, term_group: 37, flag: "cr", common: "Español CR" },
	ES_DO: { name: "Español", locale: "es_DO", slug: "es", rtl: 0, term_group: 38, flag: "do", common: "Español DO" },
	ES_EC: { name: "Español", locale: "es_EC", slug: "es", rtl: 0, term_group: 39, flag: "ec", common: "Español EC" },
	ES_ES: { name: "Español", locale: "es_ES", slug: "es", rtl: 0, term_group: 40, flag: "es", common: "Español ES" },
	ES_GT: { name: "Español", locale: "es_GT", slug: "es", rtl: 0, term_group: 41, flag: "gt", common: "Español GT" },
	ES_MX: { name: "Español", locale: "es_MX", slug: "es", rtl: 0, term_group: 42, flag: "mx", common: "Español MX" },
	ES_PE: { name: "Español", locale: "es_PE", slug: "es", rtl: 0, term_group: 43, flag: "pe", common: "Español PE" },
	ES_PR: { name: "Español", locale: "es_PR", slug: "es", rtl: 0, term_group: 44, flag: "pr", common: "Español PR" },
	ES_UY: { name: "Español", locale: "es_UY", slug: "es", rtl: 0, term_group: 45, flag: "uy", common: "Español UY" },
	ES_VE: { name: "Español", locale: "es_VE", slug: "es", rtl: 0, term_group: 46, flag: "ve", common: "Español VE" },
	ET: { name: "Eesti", locale: "et", slug: "et", rtl: 0, term_group: 47, flag: "ee", common: "Eesti" },
	EU: { name: "Euskara", locale: "eu", slug: "eu", rtl: 0, term_group: 48, flag: "basque", common: "Euskara" },
	FA_AF: { name: "فارسی", locale: "fa_AF", slug: "fa", rtl: 1, term_group: 49, flag: "af", common: "فارسی AF" },
	FA_IR: { name: "فارسی", locale: "fa_IR", slug: "fa", rtl: 1, term_group: 50, flag: "ir", common: "فارسی IR" },
	FI: { name: "Suomi", locale: "fi", slug: "fi", rtl: 0, term_group: 51, flag: "fi", common: "Suomi" },
	FO: { name: "Føroyskt", locale: "fo", slug: "fo", rtl: 0, term_group: 52, flag: "fo", common: "Føroyskt" },
	FR_BE: { name: "Français", locale: "fr_BE", slug: "fr", rtl: 0, term_group: 53, flag: "be", common: "Français BE" },
	FR_CA: { name: "Français", locale: "fr_CA", slug: "fr", rtl: 0, term_group: 54, flag: "quebec", common: "Français CA" },
	FR_FR: { name: "Français", locale: "fr_FR", slug: "fr", rtl: 0, term_group: 55, flag: "fr", common: "Français" },
	FUR: { name: "Furlan", locale: "fur", slug: "fur", rtl: 0, term_group: 56, flag: "it", common: "Furlan" },
	FY: { name: "Frysk", locale: "fy", slug: "fy", rtl: 0, term_group: 57, flag: "nl", common: "Frysk" },
	GD: { name: "Gàidhlig", locale: "gd", slug: "gd", rtl: 0, term_group: 58, flag: "scotland", common: "Gàidhlig" },
	GL_ES: { name: "Galego", locale: "gl_ES", slug: "gl", rtl: 0, term_group: 59, flag: "galicia", common: "Galego ES" },
	GU: { name: "ગુજરાતી", locale: "gu", slug: "gu", rtl: 0, term_group: 60, flag: "in", common: "ગુજરાતી" },
	HAZ: { name: "هزاره گی", locale: "haz", slug: "haz", rtl: 1, term_group: 61, flag: "af", common: "هزاره گی" },
	HE_IL: { name: "עברית", locale: "he_IL", slug: "he", rtl: 1, term_group: 62, flag: "il", common: "עברית IL" },
	HI_IN: { name: "हिन्दी", locale: "hi_IN", slug: "hi", rtl: 0, term_group: 63, flag: "in", common: "हिन्दी IN" },
	HR: { name: "Hrvatski", locale: "hr", slug: "hr", rtl: 0, term_group: 64, flag: "hr", common: "Hrvatski" },
	HSB: { name: "Hornjoserbšćina", locale: "hsb", slug: "hsb", rtl: 0, term_group: 65, flag: "de", common: "Hornjoserbšćina" },
	HU_HU: { name: "Magyar", locale: "hu_HU", slug: "hu", rtl: 0, term_group: 66, flag: "hu", common: "Magyar HU" },
	HY: { name: "Հայերեն", locale: "hy", slug: "hy", rtl: 0, term_group: 67, flag: "am", common: "Հայերեն" },
	ID_ID: { name: "Bahasa Indonesia", locale: "id_ID", slug: "id", rtl: 0, term_group: 68, flag: "id", common: "Bahasa Indonesia ID" },
	IS_IS: { name: "Íslenska", locale: "is_IS", slug: "is", rtl: 0, term_group: 69, flag: "is", common: "Íslenska IS" },
	IT_IT: { name: "Italiano", locale: "it_IT", slug: "it", rtl: 0, term_group: 70, flag: "it", common: "Italiano" },
	JA: { name: "日本語", locale: "ja", slug: "ja", rtl: 0, term_group: 71, flag: "jp", common: "日本語" },
	JV_ID: { name: "Basa Jawa", locale: "jv_ID", slug: "jv", rtl: 0, term_group: 72, flag: "id", common: "Basa Jawa ID" },
	KA_GE: { name: "ქართული", locale: "ka_GE", slug: "ka", rtl: 0, term_group: 73, flag: "ge", common: "ქართული GE" },
	KAB: { name: "Taqbaylit", locale: "kab", slug: "kab", rtl: 0, term_group: 74, flag: "dz", common: "Taqbaylit" },
	KIR: { name: "Кыргызча", locale: "kir", slug: "kir", rtl: 0, term_group: 75, flag: "kg", common: "Кыргызча" },
	KK: { name: "Қазақ тілі", locale: "kk", slug: "kk", rtl: 0, term_group: 76, flag: "kz", common: "Қазақ тілі" },
	KM: { name: "ភាសាខ្មែរ", locale: "km", slug: "km", rtl: 0, term_group: 77, flag: "kh", common: "ភាសាខ្មែរ" },
	KN: { name: "ಕನ್ನಡ", locale: "kn", slug: "kn", rtl: 0, term_group: 78, flag: "in", common: "ಕನ್ನಡ" },
	KO_KR: { name: "한국어", locale: "ko_KR", slug: "ko", rtl: 0, term_group: 79, flag: "kr", common: "한국어 KR" },
	LO: { name: "ພາສາລາວ", locale: "lo", slug: "lo", rtl: 0, term_group: 80, flag: "la", common: "ພາສາລາວ" },
	LT_LT: { name: "Lietuviškai", locale: "lt_LT", slug: "lt", rtl: 0, term_group: 81, flag: "lt", common: "Lietuviškai LT" },
	LV: { name: "Latviešu valoda", locale: "lv", slug: "lv", rtl: 0, term_group: 82, flag: "lv", common: "Latviešu valoda" },
	MK_MK: { name: "македонски јазик", locale: "mk_MK", slug: "mk", rtl: 0, term_group: 83, flag: "mk", common: "македонски јазик MK" },
	ML_IN: { name: "മലയാളം", locale: "ml_IN", slug: "ml", rtl: 0, term_group: 84, flag: "in", common: "മലയാളം IN" },
	MN: { name: "Монгол хэл", locale: "mn", slug: "mn", rtl: 0, term_group: 85, flag: "mn", common: "Монгол хэл" },
	MR: { name: "मराठी", locale: "mr", slug: "mr", rtl: 0, term_group: 86, flag: "in", common: "मराठी" },
	MS_MY: { name: "Bahasa Melayu", locale: "ms_MY", slug: "ms", rtl: 0, term_group: 87, flag: "my", common: "Bahasa Melayu MY" },
	MY_MM: { name: "ဗမာစာ", locale: "my_MM", slug: "my", rtl: 0, term_group: 88, flag: "mm", common: "ဗမာစာ MM" },
	NB_NO: { name: "Norsk Bokmål", locale: "nb_NO", slug: "nb", rtl: 0, term_group: 89, flag: "no", common: "Norsk Bokmål NO" },
	NE_NP: { name: "नेपाली", locale: "ne_NP", slug: "ne", rtl: 0, term_group: 90, flag: "np", common: "नेपाली NP" },
	NL_BE: { name: "Nederlands", locale: "nl_BE", slug: "nl", rtl: 0, term_group: 91, flag: "be", common: "Nederlands BE" },
	NL_NL: { name: "Nederlands", locale: "nl_NL", slug: "nl", rtl: 0, term_group: 92, flag: "nl", common: "Nederlands NL" },
	NL_NL_FORMAL: { name: "Nederlands", locale: "nl_NL_formal", slug: "nl", rtl: 0, term_group: 93, flag: "nl", common: "Nederlands NL formal" },
	NN_NO: { name: "Norsk Nynorsk", locale: "nn_NO", slug: "nn", rtl: 0, term_group: 94, flag: "no", common: "Norsk Nynorsk NO" },
	OCI: { name: "Occitan", locale: "oci", slug: "oci", rtl: 0, term_group: 95, flag: "occitania", common: "Occitan" },
	PA_IN: { name: "ਪੰਜਾਬੀ", locale: "pa_IN", slug: "pa", rtl: 0, term_group: 96, flag: "in", common: "ਪੰਜਾਬੀ IN" },
	PL_PL: { name: "Polski", locale: "pl_PL", slug: "pl", rtl: 0, term_group: 97, flag: "pl", common: "Polski PL" },
	PS: { name: "پښتو", locale: "ps", slug: "ps", rtl: 1, term_group: 98, flag: "af", common: "پښتو" },
	PT_AO: { name: "Português", locale: "pt_AO", slug: "pt", rtl: 0, term_group: 99, flag: "ao", common: "Português AO" },
	PT_BR: { name: "Português", locale: "pt_BR", slug: "pt", rtl: 0, term_group: 100, flag: "br", common: "Português BR" },
	PT_PT: { name: "Português", locale: "pt_PT", slug: "pt", rtl: 0, term_group: 101, flag: "pt", common: "Português PT" },
	PT_PT_AO90: { name: "Português", locale: "pt_PT_ao90", slug: "pt", rtl: 0, term_group: 102, flag: "pt", common: "Português PT ao90" },
	RHG: { name: "Ruáinga", locale: "rhg", slug: "rhg", rtl: 0, term_group: 103, flag: "mm", common: "Ruáinga" },
	RO_RO: { name: "Română", locale: "ro_RO", slug: "ro", rtl: 0, term_group: 104, flag: "ro", common: "Română RO" },
	RU_RU: { name: "Русский", locale: "ru_RU", slug: "ru", rtl: 0, term_group: 105, flag: "ru", common: "Русский RU" },
	SAH: { name: "Сахалыы", locale: "sah", slug: "sah", rtl: 0, term_group: 106, flag: "ru", common: "Сахалыы" },
	SI_LK: { name: "සිංහල", locale: "si_LK", slug: "si", rtl: 0, term_group: 107, flag: "lk", common: "සිංහල LK" },
	SK_SK: { name: "Slovenčina", locale: "sk_SK", slug: "sk", rtl: 0, term_group: 108, flag: "sk", common: "Slovenčina SK" },
	SKR: { name: "سرائیکی", locale: "skr", slug: "skr", rtl: 1, term_group: 109, flag: "pk", common: "سرائیکی" },
	SL_SI: { name: "Slovenščina", locale: "sl_SI", slug: "sl", rtl: 0, term_group: 110, flag: "si", common: "Slovenščina SI" },
	SND: { name: "سنڌي", locale: "snd", slug: "snd", rtl: 1, term_group: 111, flag: "pk", common: "سنڌي" },
	SO_SO: { name: "Af-Soomaali", locale: "so_SO", slug: "so", rtl: 0, term_group: 112, flag: "so", common: "Af-Soomaali SO" },
	SQ: { name: "Shqip", locale: "sq", slug: "sq", rtl: 0, term_group: 113, flag: "al", common: "Shqip" },
	SR_RS: { name: "Српски језик", locale: "sr_RS", slug: "sr", rtl: 0, term_group: 114, flag: "rs", common: "Српски језик RS" },
	SU_ID: { name: "Basa Sunda", locale: "su_ID", slug: "su", rtl: 0, term_group: 115, flag: "id", common: "Basa Sunda ID" },
	SV_SE: { name: "Svenska", locale: "sv_SE", slug: "sv", rtl: 0, term_group: 116, flag: "se", common: "Svenska SE" },
	SW: { name: "Kiswahili", locale: "sw", slug: "sw", rtl: 0, term_group: 117, flag: "ke", common: "Kiswahili" },
	SZL: { name: "Ślōnskŏ gŏdka", locale: "szl", slug: "szl", rtl: 0, term_group: 118, flag: "pl", common: "Ślōnskŏ gŏdka" },
	TA_IN: { name: "தமிழ்", locale: "ta_IN", slug: "ta", rtl: 0, term_group: 119, flag: "in", common: "தமிழ் IN" },
	TA_LK: { name: "தமிழ்", locale: "ta_LK", slug: "ta", rtl: 0, term_group: 120, flag: "lk", common: "தமிழ் LK" },
	TAH: { name: "Reo Tahiti", locale: "tah", slug: "tah", rtl: 0, term_group: 121, flag: "pf", common: "Reo Tahiti" },
	TE: { name: "తెలుగు", locale: "te", slug: "te", rtl: 0, term_group: 122, flag: "in", common: "తెలుగు" },
	TH: { name: "ไทย", locale: "th", slug: "th", rtl: 0, term_group: 123, flag: "th", common: "ไทย" },
	TL: { name: "Tagalog", locale: "tl", slug: "tl", rtl: 0, term_group: 124, flag: "ph", common: "Tagalog" },
	TR_TR: { name: "Türkçe", locale: "tr_TR", slug: "tr", rtl: 0, term_group: 125, flag: "tr", common: "Türkçe TR" },
	TT_RU: { name: "Татар теле", locale: "tt_RU", slug: "tt", rtl: 0, term_group: 126, flag: "ru", common: "Татар теле RU" },
	UG_CN: { name: "Uyƣurqə", locale: "ug_CN", slug: "ug", rtl: 0, term_group: 127, flag: "cn", common: "Uyƣurqə CN" },
	UK: { name: "Українська", locale: "uk", slug: "uk", rtl: 0, term_group: 128, flag: "ua", common: "Українська" },
	UR: { name: "اردو", locale: "ur", slug: "ur", rtl: 1, term_group: 129, flag: "pk", common: "اردو" },
	UZ_UZ: { name: "Oʻzbek", locale: "uz_UZ", slug: "uz", rtl: 0, term_group: 130, flag: "uz", common: "Oʻzbek UZ" },
	VEC: { name: "Vèneto", locale: "vec", slug: "vec", rtl: 0, term_group: 131, flag: "veneto", common: "Vèneto" },
	VI: { name: "Tiếng Việt", locale: "vi", slug: "vi", rtl: 0, term_group: 132, flag: "vn", common: "Tiếng Việt" },
	ZH_CN: { name: "中文 (中国)", locale: "zh_CN", slug: "zh", rtl: 0, term_group: 133, flag: "cn", common: "中文 CN" },
	ZH_HK: { name: "中文 (香港)", locale: "zh_HK", slug: "zh", rtl: 0, term_group: 134, flag: "hk", common: "中文 HK" },
	ZH_TW: { name: "中文 (台灣)", locale: "zh_TW", slug: "zh", rtl: 0, term_group: 135, flag: "tw", common: "中文 TW" },
};

export const DEFAULT_LANGUAGE = [LANGUAGES.EN_US, LANGUAGES.FR_FR, LANGUAGES.DE_DE, LANGUAGES.IT_IT];
