# TODO: write proper configuration-as-code here. (All objects previously
# featured here have diverged from their state in the actual OpenShift
# namespaces.)

- name: Deploy wp-veritas to OpenShift
  tags: setup-openshift
  include_tasks:
    file: setup-openshift.yml
    apply:
      tags: setup-openshift

- name: wp-veritas promote from test to prod
  tags: promote
  include_tasks:
    file: promote.yml
    apply:
      tags: promote
