- name: Secrets tasks
  ansible.builtin.include_tasks:
    file: 'secrets.yml'
    apply:
      tags: wpveritas.secrets
  tags: wpveritas.secrets

- name: Route tasks
  ansible.builtin.include_tasks:
    file: 'route.yml'
    apply:
      tags: wpveritas.route
  tags: wpveritas.route

- name: App tasks
  ansible.builtin.include_tasks:
    file: 'app.yml'
    apply:
      tags: wpveritas.app
  tags:
    - wpveritas.app
