- name: wp-veritas deploy
  tags: setup-openshift
  openshift:
    state: latest
    resource: Deployment
    name: "{{ wp_veritas_deploy_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          version: "{{ wp_veritas_image_version }}"
        labels:
          app: "{{ wp_veritas_app_name }}"
          author: gcharmier
          team: idev-fsd
          version: "{{ wp_veritas_image_version }}"
        name: "{{ wp_veritas_deploy_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: "{{ wp_veritas_app_name }}"
        template:
          metadata:
            labels:
              app: "{{ wp_veritas_app_name }}"
              author: gcharmier
              team: idev-fsd
              deployment: "{{ wp_veritas_deploy_name }}"
          spec:
            containers:
              - env:
                  - name: MONGO_URL
                    valueFrom:
                      secretKeyRef:
                        name: "{{ wp_veritas_secret_name }}"
                        key: mongo-url
                  - name: PORT
                    value: '3000'
                  - name: ROOT_URL
                    value: 'https://{{ wp_veritas_cname }}'
                  - name: METEOR_SETTINGS
                    valueFrom:
                      secretKeyRef:
                        name: '{{ wp_veritas_secret_name }}'
                        key: meteor-settings
                  - name: WP_VERITAS_BOT_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: '{{ wp_veritas_secret_name }}'
                        key: bot-token
                  - name: WP_VERITAS_ALERTS_TELEGRAM_IDS
                    valueFrom:
                      secretKeyRef:
                        name: '{{ wp_veritas_secret_name }}'
                        key: alert-telegram-ids
                  - name: WP_VERITAS_AWX_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: '{{ wp_veritas_secret_name }}'
                        key: awx-token
                image: "{{ wp_veritas_image_tag_current }}"
                imagePullPolicy: Always
                name: pod-wp-veritas
                ports:
                  - containerPort: 3000
                    protocol: TCP
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            terminationGracePeriodSeconds: 30
- name: wp-veritas service
  tags: setup-openshift
  openshift:
    state: latest
    resource: Service
    name: "{{ wp_veritas_svc_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ wp_veritas_svc_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ wp_veritas_app_name }}"
          author: gcharmier
          team: idev-fsd
        annotations:
          authors: idev-fsd
      spec:
        ports:
        - name: "80"
          port: 80
          protocol: TCP
          targetPort: 3000
        selector:
          app: "{{ wp_veritas_app_name }}"
          deployment: "{{ wp_veritas_deploy_name }}"
        type: ClusterIP
- name: wp-veritas route
  tags: setup-openshift
  openshift:
    state: latest
    resource: Route
    name: "{{ wp_veritas_route_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ wp_veritas_route_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ wp_veritas_app_name }}"
          author: gcharmier
          team: idev-fsd
        annotations:
          authors: idev-fsd
      spec:
        host: "{{ wp_veritas_cname }}"
        port:
          targetPort: "80"
        tls:
          termination: edge
        to:
          kind: Service
          name: "{{ wp_veritas_svc_name }}"
          weight: 100
        wildcardPolicy: None
- name: wp-veritas secrets
  tags: setup-openshift
  include_tasks: '{{ "secrets.yml" }}' 

- name: wp-veritas promote from test to prod
  tags: promote
  include_tasks: '{{ "promote.yml" }}'
