# TODO: write proper configuration-as-code here. (All objects previously
# featured here have diverged from their state in the actual OpenShift
# namespaces.)

- name: wp-veritas promote from test to prod
  tags: promote
  include_tasks: '{{ "promote.yml" }}'
