- name: "Promote wwp-test images to wwp"
  when: >-
    openshift_namespace == 'wwp'
  local_action:
    module: shell
    cmd: >-
      oc tag {{ wp_veritas_image_tag_test | regex_replace('^[^/]*/', '')  }}
      {{ wp_veritas_image_tag_prod | regex_replace('^[^/]*/', '') }}
