- name: Robot Pull
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: '{{ app_name }}-pull-secret'
        namespace: '{{ openshift_namespace }}'
      data:
        .dockerconfigjson: '{{ robot_pull }}'

- name: Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: '{{ app_name }}'
        namespace: '{{ openshift_namespace }}'
      data:
        # ROOT_URL is not a secret, and is managed in the Deployment below.
        MONGO_URL:                      '{{ MONGO_URL                      | b64encode }}'
        METEOR_SETTINGS:                '{{ METEOR_SETTINGS                | b64encode }}'

        WP_VERITAS_ALERTS_TELEGRAM_IDS: '{{ WP_VERITAS_ALERTS_TELEGRAM_IDS | b64encode }}'
        WP_VERITAS_BOT_TOKEN:           '{{ WP_VERITAS_BOT_TOKEN           | b64encode }}'

        # WP_VERITAS_AWX_URL is not a secret, and is managed in the Deployment below.
        WP_VERITAS_AWX_TOKEN:           '{{ WP_VERITAS_AWX_TOKEN           | b64encode }}'
  vars:
    MONGO_URL: >-
      mongodb://{{ secrets.mongodb.user }}:{{ secrets.mongodb.password }}@{{ secrets.mongodb.host }}.epfl.ch/{{ secrets.mongodb.name }}

    METEOR_SETTINGS: >-
      {{ _meteor_settings_struct | to_json }}
    _meteor_settings_struct:
      accred_password: '{{ secrets.accred.password }}'

    WP_VERITAS_ALERTS_TELEGRAM_IDS: >-
      {{ secrets.telegram.channels | join(",") | string }}
    WP_VERITAS_BOT_TOKEN: >-
      {{ secrets.telegram.token }}

    WP_VERITAS_AWX_TOKEN: >-
      {{ secrets.awx.token }}
