#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible-playbook" mode):
#
#   ./ansible/wpveritasible
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

set -e
cd "$(cd "$(dirname "$0")"; pwd)"

help () {
    fatal <<HELP_MSG
Usage: $0 [options]

Environment options:
  --test     Deploy to test environment.
  --prod     Deploy to production environment.

Common options:
  --list-tags      List all available tags.
  --list-tasks     List all tasks that would be executed.

Examples:
  $0
  $0 --prod
HELP_MSG
}

ensure_ansible () {
  if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
      curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
          SUITCASE_DIR=$PWD/ansible-deps-cache \
          SUITCASE_ANSIBLE_VERSION=10.7.0 \
          SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
          SUITCASE_PIP_EXTRA="kubernetes" \
          bash -x
  fi

  . ansible-deps-cache/lib.sh
  ensure_ansible_runtime
}

ensure_oc4_login () {
  local clustername="$1"; shift

  if ! oc whoami > /dev/null 2>&1 || ! oc whoami --show-server | grep -q "$cluster_url"; then
      echo "Logging into OpenShift cluster at $cluster_url..."
      oc login "$cluster_url" --web;
  else
      echo "Already logged into $cluster_url."
  fi
}

ensure_ansible

inventory_mode="test"
cluster_url="https://api.ocpitst0001.xaas.epfl.ch:6443"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --help)
      help ;;
    --test)
      shift ;;
    --prod)
      cluster_url="https://api.ocpitsp0001.xaas.epfl.ch:6443"
      inventory_mode="prod"
      shift ;;
    *)
      ansible_args+=("$1")
      shift ;;
  esac
done

ensure_oc4_login "$cluster_url"

inventories () {
  case "$inventory_mode" in
    test) echo "-i inventory/test.yml" ;;
    prod) echo "-i inventory/prod.yml" ;;
  esac
}

ansible-playbook $(inventories) playbook.yml "${ansible_args[@]}"
