all:
  hosts:
    svc0041t-wordpress:
      ansible_connection: local
      ansible_host: localhost
      inventory_environment: test
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    route:
      host: wp-veritas-test.epfl.ch
      availability: private
    tag: 6.13.12
