#!/bin/bash
#
# This is a wrapper around ansible-playbook.

# Easy to use with ansible (default is --test)
#   ./wpveritasible --test
#   ./wpveritasible --prod
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

export ANSIBLE_JINJA2_NATIVE=true
set -e
cd "$(cd "$(dirname "$0")"; pwd)"

help () {
    fatal <<HELP_MSG
Usage:

  $0 [OPTION] [ansible-args...]

Options:
  --test        Deploy to test environment (default)
  --prod        Deploy to production environment
  --help        Display this help

HELP_MSG
}

ensure_suitcase () {
    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
        curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
            SUITCASE_DIR=$PWD/ansible-deps-cache \
            SUITCASE_PIP_EXTRA="kubernetes" \
            SUITCASE_ANSIBLE_VERSION=10.7.0 \
            bash -x
    fi
    . ansible-deps-cache/lib.sh
    ensure_ansible_runtime
}

ensure_login_oc () {
    local cluster_url=$1

    if ! oc whoami > /dev/null 2>&1 || ! oc whoami --show-server | grep -q "$cluster_url"; then
        echo "Logging into OpenShift cluster at $cluster_url..."
        if ! oc login "$cluster_url" --web >> /dev/null; then
            echo "Login failed. Exiting."
            exit 1
        fi
    else
        echo "Already logged into $cluster_url."
    fi
}

ensure_suitcase

[ "$1" == "--help" ] && help

declare -a ansible_args
ansible_args=()
inventory_mode="test"
cluster_url="https://api.ocpitst0001.xaas.epfl.ch:6443"
while [ "$#" -gt 0 ]; do
    case "$1" in
        --help)
            help ;;
        --test)
            shift ;;
        --prod)
            inventory_mode="prod"
            cluster_url="https://api.ocpitsp0001.xaas.epfl.ch:6443"
            shift ;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

ensure_login_oc "$cluster_url"

inventories () {
    case "$inventory_mode" in
        test) echo "-i inventory/test.yml" ;;
        prod) echo "-i inventory/prod.yml" ;;
        *) fatal "Invalid inventory_mode" ;;
    esac
}

ansible-playbook $(inventories) "${ansible_args[@]}" playbook.yml
